GET  http://localhost:6000

###

POST  http://localhost:6000/api/auth/login
Content-Type: application/json
Authorization: Bearer 

{
    "data": {
        "username":"cyberxurde",
        "password":"password"
    }
}

###
POST http://localhost:6000/api/auth/signup
Content-Type: application/json

{
     "data": {
        "username":"cyberxurde",
         "email":"owoeye1321@gmail.com",
        "password":"password"
    }
}

###

POST http://localhost:6000/api/newUpload/upload

Content-Type: application/json

 {
    "data":{
        "name":"gadget name",
        "address":"address",
        "details":"details",
        "image":{
            "data": Buffer,
            "contentType":"image/png"
        },
        "email":"email from access token"
    }
 }

###
GET http://localhost:6000/api/read/personal
Content-Type: application/application/json
Authorization: Bearer 


###
GET http://localhost:6000/api/read/all
